[package]
name = "t"
version = "0.32.1"
authors = ["Chris Davison <c.jr.davison@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Streamlined implementation of todo.txt based on the features, formatting, and plugins that I used."

[dependencies]
chrono="0.4.6"
regex="1.1.0"
